# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsaCli < Formula
  desc "CLI for the Apple Search Ads Campaign Management API v5"
  homepage "https://github.com/TrebuhS/Apple-Search-Ads-CLI"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_darwin_amd64.tar.gz"
      sha256 "d56eaadbd263dea056d662ee8f804bb44ade19ae69b693443a7b2d14cc9667ae"

      def install
        bin.install "asa-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_darwin_arm64.tar.gz"
      sha256 "be7fc5bcc0f3a32cae93c91e022f16dd72f48d19cd2d27fa5f8043c09e4870de"

      def install
        bin.install "asa-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_linux_amd64.tar.gz"
      sha256 "35a93c35c767928900990211afc0d032f076de132d213884e7f2b9dcec8484d8"
      def install
        bin.install "asa-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_linux_arm64.tar.gz"
      sha256 "130d52b29a4b36168b9d7d10b9f7c3e5164e43866755b27a76dbae1d38afb159"
      def install
        bin.install "asa-cli"
      end
    end
  end

  test do
    assert_match "Apple Search Ads", shell_output("#{bin}/asa-cli --help")
  end
end
