# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsaCli < Formula
  desc "CLI for the Apple Search Ads Campaign Management API v5"
  homepage "https://github.com/TrebuhS/Apple-Search-Ads-CLI"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_darwin_amd64.tar.gz"
      sha256 "bd3167d81c4dbadb529fcd7d732830589b8053ee8bc9618f3372776814371d02"

      def install
        bin.install "asa-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_darwin_arm64.tar.gz"
      sha256 "810003b4d999a728975caa199326599f3b6c88c8f9d480148f802cbc1b7700b5"

      def install
        bin.install "asa-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_linux_amd64.tar.gz"
      sha256 "383cf62a3832331542259effa69d9e5f2926a715205958ad0916e384b7442923"
      def install
        bin.install "asa-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_linux_arm64.tar.gz"
      sha256 "53c502a73ff3fba834353fc6244a55211e49db6117aa2cb0805606213bdfc1f5"
      def install
        bin.install "asa-cli"
      end
    end
  end

  test do
    assert_match "Apple Search Ads", shell_output("#{bin}/asa-cli --help")
  end
end
