# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsaCli < Formula
  desc "CLI for the Apple Search Ads Campaign Management API v5"
  homepage "https://github.com/TrebuhS/Apple-Search-Ads-CLI"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_darwin_amd64.tar.gz"
      sha256 "7c124cc2f67efddbda261926071d45d13e913c514f034822b469a78b9f743741"

      def install
        bin.install "asa-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_darwin_arm64.tar.gz"
      sha256 "861ae076f12b716406d1656c370a66bfd4b2d29ef1f7bda057934befe4006c8a"

      def install
        bin.install "asa-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_linux_amd64.tar.gz"
      sha256 "ca3bd36db7dd1d1c411c1ee9301a17cfbcc3b24770b6021da9810f0d82e78f37"
      def install
        bin.install "asa-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TrebuhS/Apple-Search-Ads-CLI/releases/download/v1.0.1/asa-cli_linux_arm64.tar.gz"
      sha256 "7d49fabfa0f5893f6f94e29f1d0658ec2e898fbd39ee32711da40f4771032acc"
      def install
        bin.install "asa-cli"
      end
    end
  end

  test do
    assert_match "Apple Search Ads", shell_output("#{bin}/asa-cli --help")
  end
end
